### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by MRokas** [Evinyatar/pith#23]
After clone and ```npm install``` + ```bower install```, using ```node app.js``` gives:

```info: Library scan complete. Took 0 ms
C:\Users\rokas\Pith\pith\node_modules\async\lib\async.js:43
            if (fn === null) throw new Error("Callback was already called.");```

That is easy fixed by commenting out _pith/plugins/files/plugin.js:50_ line

But after that loading page gives this:

```
"Error: [$injector:unpr] Unknown provider: $modalProvider <- $modal <- modalHttpError <- PlayerControlService
http://errors.angularjs.org/1.5.0/$injector/unpr?p0=%24modalProvider%20%3C-%20%24modal%20%3C-%20modalHttpError%20%3C-%20PlayerControlService
minErr/<@http://192.168.1.68:3333/webui/lib/angular/angular.js:68:12
createInjector/providerCache.$injector<@http://192.168.1.68:3333/webui/lib/angular/angular.js:4397:19
getService@http://192.168.1.68:3333/webui/lib/angular/angular.js:4550:39
createInjector/protoInstanceInjector<@http://192.168.1.68:3333/webui/lib/angular/angular.js:4402:28
getService@http://192.168.1.68:3333/webui/lib/angular/angular.js:4550:39
injectionArgs@http://192.168.1.68:3333/webui/lib/angular/angular.js:4574:58
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4596:18
enforcedReturnValue@http://192.168.1.68:3333/webui/lib/angular/angular.js:4443:20
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4604:16
createInjector/protoInstanceInjector<@http://192.168.1.68:3333/webui/lib/angular/angular.js:4403:20
getService@http://192.168.1.68:3333/webui/lib/angular/angular.js:4550:39
injectionArgs@http://192.168.1.68:3333/webui/lib/angular/angular.js:4574:58
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4596:18
enforcedReturnValue@http://192.168.1.68:3333/webui/lib/angular/angular.js:4443:20
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4604:16
createInjector/protoInstanceInjector<@http://192.168.1.68:3333/webui/lib/angular/angular.js:4403:20
getService@http://192.168.1.68:3333/webui/lib/angular/angular.js:4550:39
injectionArgs@http://192.168.1.68:3333/webui/lib/angular/angular.js:4574:58
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4596:18
$ControllerProvider/this.$get</</instantiate<@http://192.168.1.68:3333/webui/lib/angular/angular.js:9855:24
nodeLinkFn@http://192.168.1.68:3333/webui/lib/angular/angular.js:8927:34
compositeLinkFn@http://192.168.1.68:3333/webui/lib/angular/angular.js:8226:13
compositeLinkFn@http://192.168.1.68:3333/webui/lib/angular/angular.js:8229:13
publicLinkFn@http://192.168.1.68:3333/webui/lib/angular/angular.js:8106:30
bootstrapApply/<@http://192.168.1.68:3333/webui/lib/angular/angular.js:1696:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://192.168.1.68:3333/webui/lib/angular/angular.js:16820:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://192.168.1.68:3333/webui/lib/angular/angular.js:16920:20
bootstrapApply@http://192.168.1.68:3333/webui/lib/angular/angular.js:1694:9
invoke@http://192.168.1.68:3333/webui/lib/angular/angular.js:4604:16
bootstrap/doBootstrap@http://192.168.1.68:3333/webui/lib/angular/angular.js:1692:5
bootstrap@http://192.168.1.68:3333/webui/lib/angular/angular.js:1712:12
angularInit@http://192.168.1.68:3333/webui/lib/angular/angular.js:1606:5
@http://192.168.1.68:3333/webui/lib/angular/angular.js:30423:7
n.Callbacks/i@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:27060
n.Callbacks/j.fireWith@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:27828
.ready@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:29619
J@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:29804
EventListener.handleEvent*n.ready.promise@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:29972
@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:30058
@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:207
@http://192.168.1.68:3333/webui/lib/jquery/dist/jquery.min.js:2:2
"
```

P.S. it says there's no software to be installed, but you have to install imagemagick for easyimage lib

**Comment by ccantill** [comment]
I haven't tested it with Angular 1.5 yet. I should probably change the dependencies to use fixed version numbers instead of "latest". Can you try changing the "angular" and "angular-route" versions to "1.3.8" in webui/bower.json and then do a bower install again?

**Comment by MRokas** [comment]
Using 1.3.8 still returns same :/

**Comment by ccantill** [comment]
Are you using the dev or the master branch?

**Comment by MRokas** [comment]
I had that error in master branch, and now am trying dev. gimme a minute to check if it occurs in master.

**Comment by Evinyatar** [comment]
I managed to reproduce it locally. Try again on dev; I fixed all the bower versions.

**Comment by MRokas** [comment]
Yes. that solved the error.

Thanks!

**Comment by Evinyatar** [comment]
Happy to help, and even happier to see a new user for my software :)
