### ISSUE TITLE
unable to start app.js

### ISSUE THREAD

**Issue by k2patel** [Evinyatar/pith#25]
I'm getting following error while trying to run the app.

[k2patel@fpaste pith]$ node app.js 
Listening on 192.168.1.102:3333
info: Starting library scan
info: Library scan complete. Took 6 ms

/home/k2patel/pith/node_modules/async/dist/async.js:839
            if (fn === null) throw new Error("Callback was already called.");
                                   ^
Error: Callback was already called.
    at /home/k2patel/pith/node_modules/async/dist/async.js:839:36
    at /home/k2patel/pith/plugins/library/scanner.movie.js:72:29
    at /home/k2patel/pith/plugins/files/plugin.js:50:17
    at Object.oncomplete (fs.js:108:15)

**Comment by k2patel** [comment]
After changing to dev, branch and setting angular#1.3.8, server has started.

**Comment by k2patel** [comment]
But i can not play anyting since it's keep saying that no player selected.
Not sure how to troubleshoot.
I'm no expert in node.js

**Comment by Evinyatar** [comment]
You should see a drop down in the top right corner; that will list all available UPnP/DLNA renderers on the network. If that list is empty, then no supported players are found. Local playback in the browser is currently not yet supported (but planned), and I'm also planning on adding AirPlay support in the future. But for now, it's just UPnP/DLNA.
